POST http://localhost:5000/api/auth/register
Content-Type: application/json


{
    "username" : "Phan",
    "password" : "nghiadn12"
}

####
POST  http://localhost:5000/api/auth/login
Content-Type: application/json


{
    "username" : "John5",
    "password" : "nghiadn12"
}
